### ISSUE TITLE
Set up google analytics

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse.org#10]
Before the dataverse.org launch, we need to set up Google analytics

**Comment by jggautier** [comment]
Analytics is on the two dataverse.org subdomains that have the guides on Sphinx pages: [best-practices.dataverse.org](http://best-practices.dataverse.org/) and [guides.dataverse.org](http://guides.dataverse.org/en/latest/), and the analytics are being sent to and can be retrieved from the same place that dataverse.org analytics is being sent (the same tracking ID is being used).

The only other Dataverse-owned pages linked to from dataverse.org are the Dataverse Community Meeting pages (https://projects.iq.harvard.edu/...). 2015, 2016 and 2017 have Google Analytics scripts, but they're not using the same tracking ID that dataverse.org is using, so their analytics aren't being sent to the same account that's getting the dataverse.org analytics.

Some questions to answer:
Do we need analytics for the community meeting sites? Have they been looked at/helpful?
Do we need those analytics to be sent to the account that's getting the dataverse.org analytics?

**Comment by jggautier** [comment]
I'm going to close this issue since Google Analytics is on dataverse.org. Anyone following, please feel free to create issues for adding the tracking script to other sites, some of which I mentioned in [this github issue comment](https://github.com/IQSS/dataverse.org/issues/10#issuecomment-344017262).
