### ISSUE TITLE
Make Top Navigation Bar Match dataverse.org for Sphinx Projects

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#23]
Based on our meeting, I created the two new Sphinx projects under docs ("Community" and "Best Practices") on top of our Dataverse Guides http://docs.dataverse.org/en/4.0/ but will need to assign this to a developer to help figure out how we get the top navigation to look the same across all dataverse.org (similar to zelig projects). @mheppler I'm assigning to you to help triage for now but let me know @raprasad or @pdurbin if this should be assigned to another developer.

**Comment by raprasad** [comment]
This is done
