### ISSUE TITLE
menu: secondary "dropdown" for guides isn't working on sphinx pages

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse.org#25]
may be due to two different versions of jquery being loaded.  See #26 

![replication_guidelines_ _dataverse_best_practices_1_0_documentation](https://cloud.githubusercontent.com/assets/1036060/5463137/269d5268-8548-11e4-8153-f4e653eb1c00.png)

**Comment by pdurbin** [comment]
The only reason why the best practices site is still up is https://github.com/IQSS/dataverse.harvard.edu/issues/7 for a single page.

We'll be taking it down soon. Closing.
