### ISSUE TITLE
Best practices docs call 2 different versions of jquery

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse.org#26]
_Note: This causes an error in the console but page does render--may be slowing down menu rendering._

from a view source on:  http://best-practices.dataverse.org/index.html
1.   `<script type="text/javascript" src="_static/jquery.js"></script>`
2. `<script type="text/javascript" src="_static/js/jquery-1.11.0.min.js"></script>`

``` html
<script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="_static/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="_static/js/jquery-fix.js"></script>
    <script type="text/javascript" src="_static/bootstrap-3.1.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="_static/bootstrap-sphinx.js"></script>
```

**Comment by pdurbin** [comment]
These days (over 4 years later) the best practices site is on life support (we tried to kill it once): https://github.com/IQSS/dataverse.harvard.edu/issues/7

The code for the guides lives in the main repo so if there's any issue, it should be opened at https://github.com/IQSS/dataverse/issues

Closing.
