### ISSUE TITLE
About Page: improvements

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse.org#29]
The about page needs a couple of images and the publications and presentations widget:

1) images to include under about the project:
http://guides.dataverse.org/en/latest/user/dataverse-management.html
http://guides.dataverse.org/en/latest/user/dataset-management.html

2) Presentations and Publications widgets (This could be display as a right sidebar in the page):

<script type="text/javascript" src="http://datascience.iq.harvard.edu/profiles/openscholar/modules/os/modules/os_boxes/misc/os_boxes.resize_parent.js"></script>

<iframe class="web-widgets-iframe" src="http://datascience.iq.harvard.edu/widget/embed/1418878134/iframe" scrolling="no" frameborder="0"></iframe>

<script type="text/javascript" src="http://datascience.iq.harvard.edu/profiles/openscholar/modules/os/modules/os_boxes/misc/os_boxes.resize_parent.js"></script>

<iframe class="web-widgets-iframe" src="http://datascience.iq.harvard.edu/widget/embed/1418878054/iframe" scrolling="no" frameborder="0"></iframe>

**Comment by pdurbin** [comment]
This issue is over 4 years old and I doubt it's relevant anymore. Closing.
