### ISSUE TITLE
Change the Twitter username and URL in the Footer

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#32]
Once I change our twitter username from thedataorg to dataverseorg the twitter URL in the footer will no longer point to the right page on twitter (broken link).

Since this change takes a second to make on twitter I will wait till the changes are made on dataverse.org  website before I push the change in Twitter.

- [x] The URL needs to change to: https://twitter.com/dataverseorg
- [x] The Twitter widget will need to point to the new **dataverseorg** username

**Comment by eaquigley** [comment]
Done and done! Closing ticket.

**Comment by pdurbin** [comment]
I just updated the Twitter username here too: https://github.com/IQSS/dataverse/commit/91198858aa540bda462a61aea18c42fa667fc223
