### ISSUE TITLE
Repository Cards: Responsive Solution

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse.org#34]
Currently, the cards flip but they take up a lot of screen room and are hard to close on a mobile device. We can investigate this more in January and see if we can figured out a solution. Additionally, the gray card explaining these are repository cards doesn't adjust on a mobile device to fit the screen.

**Comment by pdurbin** [comment]
These cards haven't existed since we've moved to dataverse.org to OpenScholar years ago. Closing.
