### ISSUE TITLE
Fix URL to Abacus Dataverse repository on homepage

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#35]
The URL is pointing to the general library website but should point directly to their Dataverse instance:

http://dvn.library.ubc.ca/dvn/

As seen here: https://docs.google.com/document/d/1w6S5svVauDALRiz8WCH1mmFxIMCJxzG1-1cttdY7mOo/edit?usp=sharing

**Comment by mheppler** [comment]
Updated the URL.

**Comment by posixeleni** [comment]
I just received an email from the ABACUS Dataverse people that their URL on our homepage is now erroneously pointing to the University of Alberta Dataverse rather than the ABACUS (British Columbia) The correct URL is: http://dvn.library.ubc.ca/dvn/

@mheppler can you please fix this asap?

**Comment by mheppler** [comment]
Fixed the link.

**Comment by eugene-barsky** [comment]
Hello, the UBC Dataverse box on the dataverse homepage still points to the University of Alberta instance of Dataverse rather than to ours - http://dvn.library.ubc.ca/dvn/

Could this be fixed?

Thanks!

Eugene

**Comment by posixeleni** [comment]
Hi Eugene,

If you could please check the Abacus URL on our dataverse.org webpage the issue should now be resolved. Apologies for the delay but we were experience issues with our system updating correctly.

Please hit refresh on the page before trying it out just to be on the safe side (had to do this in Chrome).

Please let me know if this is now resolved and if I can help with anything else.

Have a great weekend!

Eleni

--
Eleni Castro
Research Coordinator, Data Acquisition and Archiving, Data Science
IQSS, Harvard University
http://www.iq.harvard.edu/people/eleni-castro

We're redesigning Dataverse and want your feedback! Please check out our Beta Site.<http://dataverse-demo.iq.harvard.edu/>

**Comment by eugene-barsky** [comment]
Works now - thanks and have a great weekend!

E
