### ISSUE TITLE
Issue w/ some flip cards on Homepage using Safari 8.0.2

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#37]
Issue reported by Jon at Odum when trying out their particular Odum flip card on the homepage. This issue is showing up on Safari and only for some of the flip cards
![image](https://cloud.githubusercontent.com/assets/5013837/5538662/570cb190-8a85-11e4-9794-735ccb2254ac.png)

**Comment by pdurbin** [comment]
These flip cards haven't existed since we moved dataverse.org to OpenScholar years ago. Closing.
