### ISSUE TITLE
Change UiT Dataverse Repository Flip Card on Homepage

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#38]
Here is some feedback from UiT on the content of their flip card on the Homepage:

Your new homepage looks very nice. Congratulations on that.
 
Regarding the info about and link to our Dataverse, there are a couple of things we would like you to change:
-          The name you use should be the name of our service: **UiT Open Research Data**
-          The information underneath this name should read like this, to get the name of the institution correct: **“Open for researchers affiliated with UiT The Arctic University of Norway to deposit data.”**

**Comment by mheppler** [comment]
Updated the name and info.
