### ISSUE TITLE
Change DANS Dataverse Logo on Flip Card (Homepage)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#39]
Feedback from DANS Dataverse about their flip card:

*I very much like the design of the dataverse.org homepage.  In general, we use the attached logo in publications. The difference with the current image is the addition of "Data Archiving and Networked Services" in red over the DANS letters. If you could use this instead, that would be great.*

![image](https://cloud.githubusercontent.com/assets/5013837/5538892/7dcf2288-8a88-11e4-99d4-6fe58138709a.png)

**Comment by mheppler** [comment]
Updated the logo.
