### ISSUE TITLE
Change University of Alberta Libraries Logo on Flip Card (Homepage)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#40]
UoA reviewed the wording for their Dataverse on the homepage and are OK with it. However, they would like us to change the logo to the one they have for their Libraries

![image](https://cloud.githubusercontent.com/assets/5013837/5614261/2b6e33d2-94bd-11e4-909c-2037fb31c9ce.png)

**Comment by mheppler** [comment]
Updated the logo.
