### ISSUE TITLE
Feedback from Odum on dataverse.org homepage

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#41]
Email from Jon about dataverse.org homepage:

> Eleni

> I will need to gather consensus from our group but I do like the Odum image.

> It seems though the the card flips are not working quite right. (tracked in another ticket)
>Some of the cards over write the text and make it unreadable. The Odum is one of them.

>I would also like to place the Odum service levels on the Odum Card.
>Thu-Mai and Sophia can get you text for that.

>If you want the .ORG to promote the new community better  we should highlight the selection of which >Dataverse to use better. The text does say this but with so much text in the add window it gets lost.
>Maybe we could have Step 1 be Select a Dataverse Appropriate for your Community for Add and >make the Across all DVNs in the search a little bigger text.

>Over all I really like it. If we can get other DVNs to advertise service through this it would be great.

>We hope to have a SECURE Odum DVN coming soon to our offerings

>jon

Need to follow-up with Jon to get the right content for Odum to display on the homepage

**Comment by posixeleni** [comment]
Followed-up with Odum and received the following updates for their dataverse card on the homepage:

New logo: 
![image](https://cloud.githubusercontent.com/assets/5013837/5922609/fe2135c2-a61a-11e4-8778-81995470cd7b.png)

Update card description to say the following:
“Open for all researchers worldwide from all disciplines to deposit data. The Odum Institute also offers multiple data curation service levels, for more information click here.” 

Also make sure "here" hyperlinks to: http://www.irss.unc.edu/odum/contentSubpage.jsp?nodeid=661

**Comment by mheppler** [comment]
Added new logo, text, URL to dataverse cards for ODUM and Abacus. Added HTML functionality for the descriptions to the homepage.
