### ISSUE TITLE
Copyright: Change from 2014 to 2015

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse.org#44]
For future, look for a way to automate this.

**Comment by raprasad** [comment]
dataverse.org is already set to update with the current year.
- https://github.com/IQSS/dataverse.org/blob/master/dataverse_org/templates/base.html#L54
- ```{% now "Y" %}`` in the snippet below pulls in the current date and displays the year
```
 <p>Copyright &copy; {% now "Y" %}, The President &amp; Fellows of Harvard College</p>
```
