### ISSUE TITLE
Revise and Update Best Practices & Getting Started Guides After 4.0 Release

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#45]
Will need to revise the content in "Getting Started" and "Best Practices" guides once 4.0 is released. This is a placeholder for us to keep track of this item.

**Comment by pdurbin** [comment]
The best practices site is being shut down. We shut it down a few weeks ago and brought it back to life temporarily because there was still something linking to it. For details, see https://github.com/IQSS/dataverse.harvard.edu/issues/7

Closing.
