### ISSUE TITLE
Clean up Getting Started Page

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#46]
Discussed with @mcrosas the following changes to be made in the short-term for the Getting Started page. Will further refine this page after 4.0 is released (tracked in a separate ticket #45 )
- Make sure references to the repository instances are all written as "Dataverse Repository".
- Where available/applicable: add links to guides or webpages.
- Change main header text from "Getting Started" to "Getting Started: Add Data"

**Comment by jggautier** [comment]
The first two points have been addressed:
- In the Getting Started pages, references to the repository instances are all written as "Dataverse Repository".
- The pages include links to webpages and Dataverse guides. I updated a few dead links.

> Change main header text from "Getting Started" to "Getting Started: Add Data"

@mercecrosas. Could you recall what was meant by "the main header text"? Was there a Getting Started main page with links to each of the four Getting Started pages (researchers, journals, etc)?

**Comment by pdurbin** [comment]
@jggautier judging from ea77d98 I think you're right. Years ago one could see the words "Getting Started". This is no longer the case so I'm closing this issue.

<img width="1090" alt="Screen Shot 2019-04-07 at 9 08 03 PM" src="https://user-images.githubusercontent.com/21006/55692827-601dee80-5979-11e9-8436-f626cd1d08b8.png">
