### ISSUE TITLE
Updated blurb about WorldMap Dataverse integration (Data Science)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse.org#47]
> Hi Eleni,
> 
> I do not have an updated spiel.  However, feel free to spend me a ticket (or something) to make one.
> 
> Thanks,
> 
> Raman

On Feb 5, 2015, at 1:46 PM, Castro, Eleni ecastro@fas.harvard.edu wrote:

Hi Raman,

Do you by any chance have any updated text/spiel I can use for our Collaborations page http://datascience.iq.harvard.edu/collaborations that explains the WorldMap-Dataverse Integration. Should we call it GeoConnect?

Here's what we currently have:

WorldMap-Dataverse Integration

The Boston Area Research Initiative (BARI), in collaboration with the Center for Geographic Analysis (CGA) at Harvard are working on a two year project (2014-2015) integrating WorldMap with Dataverse. This integration will provide support for geospatial visualization of datasets in Dataverse. For more information check out our blog post and stay tuned for updates on this project's progress.

Let me know if this can be updated. 
Thanks!
Eleni

Note: this is is for the Data Science site but since we dont have an issue tracker for that site I am putting this ticket on here.

**Comment by pdurbin** [comment]
> Note: this is is for the Data Science site

Does http://dataverse.org link to http://datascience.iq.harvard.edu/collaborations ? It probably should! :)

**Comment by pdurbin** [comment]
We talked about WorldMap at https://dataverse.org/blog/dataverse-462

Besides, there's a good amount of documentation in our guides. Here for example: http://guides.dataverse.org/en/4.12/admin/geoconnect-worldmap.html 

I think that's enough. Closing this 4 year old issue.
