### ISSUE TITLE
Change Roadmap Link in Menu bar

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse.org#50]
@mheppler (when you have a chance) change the Roadmap link in dataverse.org to point directly to: https://github.com/IQSS/dataverse/milestones

Apply the same menu bar to the other sphinx projects:

http://guides.dataverse.org/en/latest/
http://best-practices.dataverse.org/data-citation/
http://community.dataverse.org/

**Comment by pdurbin** [comment]
These days the Roadmap link under Software at dataverse.org points to https://dataverse.org/goals-roadmap-and-releases

There's really nothing to fix here in this repo so I'm closing this issue. The guides do link to the roadmap from a few pages (mostly the dev guide) but if we want to edit the menu in the top nav, the code is in https://github.com/IQSS/dataverse
