### ISSUE TITLE
Pull stats from 4.0 instead of 3.6

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse.org#53]
Stats are being scraped from 3.6

@eaquigley @scolapasta @mheppler

**Comment by jggautier** [comment]
@scolapasta, @mheppler Were the stats being referred to here from an earlier version of dataverse.org?

**Comment by jggautier** [comment]
Closing this issue. Spoke with @mheppler, who said this is probably referring to a version of dataverse.org being worked on before miniverse metrics were added to the site.
