### ISSUE TITLE
Path to favicon and githubicon.png in layout.html

### ISSUE THREAD

**Issue by borsna** [IQSS/dataverse.org#54]
In the following lines:
https://github.com/IQSS/dataverse.org/blob/master/docs/sphinx_bootstrap_theme/bootstrap/layout.html#L94
https://github.com/IQSS/dataverse.org/blob/master/docs/sphinx_bootstrap_theme/bootstrap/layout.html#L131
The image paths is not put trough the `pathto()` function.
I am not familiar with the templating language but i guess it should be something along the lines of:
`{{ pathto('_static/images/githubicon.png') }}`

**Comment by pdurbin** [comment]
@borsna I don't believe this issue is still relevant because dataverse.org was moved from the Django+Sphinx code in this git repo to OpenScholar. I'm closing this issue but if you're still seeing a problem, please let us know!
