### ISSUE TITLE
Broken Link - About/Data Science team

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse.org#56]
"For more information, see the Data Science team at IQSS."

http://datascience.iq.harvard.edu/data-science-team

That's a blank page.

" The URL might be incorrect or have changed. Please go back to the homepage"

**Comment by jggautier** [comment]
I think dead link is only on the old Sphinx [Dataverse Advisory Team page](http://community.dataverse.org/advisory-team.html), which has been replaced with [the OpenScholar Advisory Team page](https://dataverse.org/advisory), which has different content and doesn't have this link.

Closing this issue
