### ISSUE TITLE
redirect roadmap.iq.harvard.edu

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse.org#59]
The milestone reader on AWS has been removed.

Please set these two urls:
  1.  ```http://roadmap.iq.harvard.edu```
  1.  ```http://roadmap.datascience.iq.harvard.edu``` 

.. to Redirect to:
  -   ```https://github.com/IQSS/dataverse/milestones```

Thanks

**Comment by pdurbin** [comment]
@raprasad what about http://roadmap.datascience.iq.harvard.edu ?

**Comment by raprasad** [comment]
Thanks for remembering. Yes, please do the same for that url--the main description is updated

**Comment by pdurbin** [comment]
Done in da6bfa0 but it may take a while for DNS to propagate.
