### ISSUE TITLE
Update dataset citation image in best practices documentation

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.org#61]
An image on [the data citation page](http://best-practices.dataverse.org/data-citation/index.html) of the best practices documentation needs to be updated so that the parts of the dataset citation are in the right order. The order in the image is:

Author(s), Year, Dataset Title, **Data Repository or Archive, Version, Global Persistent Identifier**

<kbd>![32087405-8acbdcca-baa9-11e7-956d-8ce380d32574](https://user-images.githubusercontent.com/18374574/32303232-bbc4185e-bf3d-11e7-84dc-592d4d9ed291.png)</kbd>

We should replace it with this image, which has the current order:

Author(s), Year, Dataset Title, **Global Persistent Identifier, Data Repository or Archive, Version**

<kbd>![generic-citation-2](https://user-images.githubusercontent.com/18374574/32303291-fdd3dd6a-bf3d-11e7-8ca9-67a83972c6db.png)</kbd>

**Comment by pdurbin** [comment]
It's been a while since we ran a build but I thing the job is https://build.hmdc.harvard.edu:8443/job/best-practices.dataverse.org/

![screen shot 2017-11-02 at 2 56 53 pm](https://user-images.githubusercontent.com/21006/32344707-2303fbe2-bfde-11e7-982a-749d10351f2d.png)

**Comment by jggautier** [comment]
This is updated now on OpenScholar, http://best-practices.dataverse.org/data-citation/index.html, and Sphynx, https://dataverse.org/best-practices/data-citation.

(When https://github.com/IQSS/dataverse.org/issues/62 is resolved, the page that's hosted on OpenScholar, http://best-practices.dataverse.org/data-citation/index.html, will be the only copy available.)
