### ISSUE TITLE
Replace installation map powered by miniverse

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.org#66]
See @pdurbin's post below for the goals for the new map.

Related to issue: https://github.com/IQSS/miniverse/issues/64

**Comment by pdurbin** [comment]
Here are the notes I wrote up after today's design meeting:

Problems with the old map:

- 12 x $113 per year
- security vulnerabilities
- links to installations on aren't opening in new browser tab: https://github.com/IQSS/miniverse/issues/64
- funky grey dots: https://github.com/IQSS/miniverse/issues/65
- low res images
- heavyweight and no development since 2016
- mobile hostile (OpenScholar)

Goals for new map:

- Lighterweight
- Badges
  - CoreTrustSeal
  - GDCC member

Bugs with new map:

- not stable in window
- better tile layer
- dots too big
- more detailed, accurate info
  - dots are in the wrong spot
- no logos in popups

**Comment by djbrooke** [comment]
For the purposes of this sprint, we said we'd timebox this to 4 hours (and that's why we gave it a small)

**Comment by TaniaSchlatter** [comment]
Design considerations for next iteration for a map for Dataverse.org:

Dot details – Dataverse dark orange, white border, smaller dots:

- const markerFillColor = '#C55B28';
- const markerBorderColor = '#ffffff';
- const markerStyle = `
  background-color: ${markerFillColor};
  border-radius: 50%;
  width: .6rem;
  height: .6rem;
  display: block;
  transform: rotate(45deg);
  border: 1px solid ${markerBorderColor}
`;

- Map to try – I like the look and level of detail of of the following map. The code from Leaflet has "API Key Required" I can pick a different map if that makes it so we can't use it. 


Details need to be worked out in terms of dot position, zoom and scroll behavior as noted in the criteria above: 

- Provider names for leaflet-providers.js
- Thunderforest.Neighbourhood
- Plain JavaScript:

var Thunderforest_Neighbourhood = L.tileLayer('https://{s}.tile.thunderforest.com/neighbourhood/{z}/{x}/{y}.png?}', {
	attribution: '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
	maxZoom: 22
});

UPDATED 1/6/2020... here is the what the map from https://github.com/IQSS/dataverse-installations looks like currently:

![Screen Shot 2020-01-06 at 2 24 59 PM](https://user-images.githubusercontent.com/687227/71842725-56ecba00-3090-11ea-9c13-8f64d69d51d2.png)

**Comment by djbrooke** [comment]
Hi @pdurbin @TaniaSchlatter @shlake @poikilotherm, as I mentioned in the other repo I reverted the changes included in https://github.com/IQSS/dataverse-installations/pull/20 in https://github.com/IQSS/dataverse-installations/pull/21. Sorry again for the confusion. 

I got a chance to catch up with @TaniaSchlatter earlier today and I propose that we use this issue to get the design changes and other changes that we feel are needed to get this to replace the current dataverse.org map. Once it's in a state that the IQSS design team feels is acceptable, we can switch out the map and investigate further changes.

**Comment by mheppler** [comment]
Created a new branch [`new-map-background-styles`](https://github.com/IQSS/dataverse-installations/tree/new-map-background-styles) in the dataverse-installations repo, that includes the change to the CartoDB.Voyager map layer that does not require an API key, as well as the changes to the size and color of the dots, plus removes the table with additional information (new `map.html` file) and styles the fonts to match dataverse.org.

@TaniaSchlatter please review the screenshots, and let me know if this looks kosher. If you approve of these, Phil can merge my branch and we can update the map at: https://iqss.github.io/dataverse-installations/map.html and link to that on dataverse.org.

![Screen Shot 2020-01-06 at 4 40 18 PM](https://user-images.githubusercontent.com/687227/71850856-3e39cf80-30a3-11ea-9fef-6e12fd630350.png)

![Screen Shot 2020-01-06 at 4 27 44 PM](https://user-images.githubusercontent.com/687227/71850819-2f531d00-30a3-11ea-98fa-094fc6a41266.png)

**Comment by mheppler** [comment]
Pushed to dataverse.org. Closing.

![Screen Shot 2020-01-07 at 11 45 25 AM](https://user-images.githubusercontent.com/687227/71912311-46494c00-3143-11ea-847f-e1de52c32b65.png)
