### ISSUE TITLE
Post Support Site Launch - What about best-practices.dataverse.org?

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse.org#67]
First recorded in https://github.com/IQSS/dataverse.harvard.edu/issues/26.

There were some odds results in Google for dataverse.org that need to be cleaned out.

- review/delete content on best-practices.dataverse.org
- ~edit robots.txt to exclude more urls like "/users", "best-practices.dataverse.org", "guides.dataverse.org/en/latest/_downloads/", "/?pagename=Main.UNF", "/forum#!topic/gevent/5x5PM58d7YQ"... create sitemap.xml?~

**Comment by mheppler** [comment]
After it was determined how difficult it is to edit the robots.txt in OpenScholar (because you can't), I went ahead and changed the scope of this to be specifically about all things "best-practices.dataverse.org".

_More info to come..._

- https://support.dataverse.harvard.edu/policies (UPDATE: removed 404 "here" link, https://github.com/IQSS/dataverse.org/tree/master/docs/best_practices/source/harvard-policies)
- https://dataverse.org/harvard-dataverse-policies (_"The URL might be incorrect or have changed."_)
- https://github.com/IQSS/dataverse.org (README.md, http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html)

_Related to..._

- https://github.com/IQSS/dataverse.harvard.edu/issues/7
- https://github.com/IQSS/dataverse.harvard.edu/issues/24

**Comment by pdurbin** [comment]
That best-practices host was on some VM that isn't even around anymore:

```
$ host best-practices.dataverse.org
best-practices.dataverse.org is an alias for dvnweb-vm3.hmdc.harvard.edu.
dvnweb-vm3.hmdc.harvard.edu has address 140.247.115.143
```

Closing.
