### ISSUE TITLE
add docs.dataverse.org

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse.org#9]
- [ ] register docs.dataverse.org
- [ ] on VM, make directory  /var/www/docs.dataverse.org/
- [ ] Add apache virtual host.  example:

```
<VirtualHost *:80>
ServerName docs.dataverse.org
DocumentRoot /var/www/docs.dataverse.org/
</VirtualHost>
```

```
- file to update: [deploy/vagrant-centos-dataverse_org.conf](https://github.com/IQSS/dataverse.org/blob/master/deploy/vagrant-centos-dataverse_org.conf)
```
- [ ] modify jenkins job to build/copy docs
  - doc source:  
     [IQSS/dataverse repo](https://github.com/IQSS/dataverse/tree/master/doc)
- [ ] version the docs
  -  docs.dataverse.org/4.0/
  -  docs.dataverse.org/4.1/
  -  etc

**Comment by pdurbin** [comment]
We went with http://guides.dataverse.org instead. Closing.
